"""Verified USB constants for the Sony InfoCarry."""

SONY_VENDOR_ID = 0x054C
INFOCARRY_PRODUCT_ID = 0x001E

USB_REQUEST_GET_DESCRIPTOR = 0x06
USB_REQUEST_GET_INTERFACE = 0x0A

USB_DESCRIPTOR_DEVICE = 0x01
USB_DESCRIPTOR_CONFIGURATION = 0x02
USB_DESCRIPTOR_INTERFACE = 0x04
USB_DESCRIPTOR_ENDPOINT = 0x05

USB_REQUEST_TYPE_DEVICE_IN = 0x80
USB_REQUEST_TYPE_INTERFACE_IN = 0x81

USB_TRANSFER_TYPE_NAMES = {
    0: "control",
    1: "isochronous",
    2: "bulk",
    3: "interrupt",
}
